### ISSUE TITLE
Frames - BlzFrameSetScale doesn't work

### ISSUE THREAD

**Issue by InsanityAI** [Warcraft-III-Community-Edition/W3CE#43]
For text frame (in Allies menu) I have the following:
```lua
...
    frame = BlzCreateFrameByType("TEXT", "", parentFrame, "", 0)
    BlzFrameSetPoint(frame, FRAMEPOINT_CENTER, parentFrame, FRAMEPOINT_CENTER, 0.00, 0.00)
    BlzFrameSetText(frame, "You tried")
    BlzFrameSetTextAlignment(frame, TEXT_JUSTIFY_MIDDLE, TEXT_JUSTIFY_CENTER)
    BlzFrameSetSize(frame, 0.10, 0.05)
    BlzFrameSetScale(frame, 4)
```

And for the clock, I hide it like this:
```lua
local thisframe = BlzFrameGetChild(BlzFrameGetChild(BlzGetOriginFrame(ORIGIN_FRAME_GAME_UI, 0), 5),0)
BlzFrameSetScale(thisframe, 1.5) --makes the clock fuck off - Works only on RF
```
# Results

RF:
![image](https://github.com/user-attachments/assets/6672da4b-d023-4196-aefd-dc5a4124a22f)

CE:
![image](https://github.com/user-attachments/assets/b31298a9-ae7d-4eec-bd02-563df59a7416)

Since in CE, the text doesn't look scaled, and the clock is still in sight it indicates that BlzFrameSetScale doesn't properly work.

Here's the test map:

[Lua TestMap.zip](https://github.com/user-attachments/files/16280558/Lua.TestMap.zip)

**Comment by cipherxof** [comment]
This has been fixed for the next release.
